### ISSUE TITLE
Any plans towards 6.14 Beta?

### ISSUE THREAD

**Issue by IZ1IVA** [jkingan/ladyheather#1]
Hi, thank you for your work on modernizing the macOS version of Lady Heather!
I was wondering whether you might be interested in working on 6.14 Beta sources to keep the project up to date...

Any thoughts?

Cheers!

**Comment by jkingan** [comment]
I do have a version that is updated. I re-pulled the 6.14 source from the EEVBlog thread (is that the only place it exists??) and it looks like it's the same thing. I checked it all into a new branch called six14 and pushed it up. It builds on macOS and seems to run. Unfortunately I can't fully test it because my sole USB->Serial cable failed. Without some testing, I'm hestitant to merge it in, but feel free to pull it down and give it a try!

I've got another cable coming so I can test it myself here soon with the couple of devices I have on hand.

**Comment by IZ1IVA** [comment]
> Without some testing, I'm hestitant to merge it in, but feel free to pull it down and give it a try!

I'd like to, but I don't have Xcode set up at the moment. I'll see if I can do it on the weekend. Thank you for the reply!

**Comment by jkingan** [comment]
I managed to find a working cable and got everything going last night. I did find a bug I now remember I ran into when I originally tried to merge everything. But I got it fixed and it ran all day and didn't seem to have any problems. 

I went ahead and merged the new code into the master branch. I also put up some new macOS binaries you can grab from [https://kg7nux.org/ladyheather-6.14.1.zip](https://kg7nux.org/ladyheather-6.14.1.zip) These need macOS 11+ and should run on Intel and Apple Silicon machines.

**Comment by IZ1IVA** [comment]
Hahaha you got me!
